[project]
name = "gree-cli"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "cyclopts>=3.21.0",
    "greeclimate>=2.1.0",
    "pydantic>=2.11.7",
]

[project.scripts]
gree = "gree_cli.app:app"

[tool.uv]
package = true
